config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :index] do
    member do
      get :following, :followers
    end
   end
   resources :relationships,   only: [:create, :destroy]
   root to: "events#index"
   resources :events do
    resources :comments, only: :create
    resources :menus, only: [:index, :new, :create]     
    resources :likes, only: [:create, :destroy]
  end
  resources :menu_selects, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :event # eventsテーブルとのアソシエーション
  belongs_to :user  # usersテーブルとのアソシエーション
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  mount_uploader :image, ImageUploader
  
  # コメント
  has_many :comments
  # いいね
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
  # メニュー
  has_many :menus, dependent: :destroy
  accepts_nested_attributes_for :menus, allow_destroy: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :event
  validates_uniqueness_of :event_id, scope: :user_id
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :event
  has_many :menu_sets, dependent: :destroy
  accepts_nested_attributes_for :menu_sets, allow_destroy: true


  def selectable_menus
    Menu.all
  end

end

app/models/menu_select.rb
class MenuSelect < ApplicationRecord
  validates :menu_name, presence: true, uniqueness: true
end

app/models/menu_set.rb
class MenuSet < ApplicationRecord
  belongs_to :menu

  def selectable_menus
    MenuSet.all
  end
end

app/models/number_unit.rb
class NumberUnit < ApplicationRecord
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"
  validates :follower_id, presence: true
  validates :following_id, presence: true

end

app/models/rep_unit.rb
class RepUnit < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :events, dependent: :destroy
  validates :name, presence: true, length: { maximum: 6 }
  validates :image, presence: true

  # フォロー機能
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy

  has_many :followings, through: :following_relationships
 
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
 
  has_many :followers, through: :follower_relationships
 
   def following?(other_user)
     following_relationships.find_by(following_id: other_user.id)
   end
 
   def follow!(other_user)
     following_relationships.create!(following_id: other_user.id)
   end
 
   def unfollow!(other_user)
     following_relationships.find_by(following_id: other_user.id).destroy
   end
  # ユーザー検索機能
  def self.search(input, id)
    return nil if input == ""
    User.where(['name LIKE ?', "%#{input}%"] ).where.not(id: id).limit(10)
  end

  # いいね
  has_many :likes, dependent: :destroy
  has_many :liked_events, through: :likes, source: :event
  def already_liked?(event)
    self.likes.exists?(event_id: event.id)
  end

  # コメント
  has_many :comments

  mount_uploader :image, ImageUploader
end

app/controllers/events_controller.rb
class EventsController < UsersController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, except: [:index, :show]

  # GET /events
  # GET /events.json
  def index
    @all_events = Event.all.includes(:user)
    @user = User.find(current_user.id)
    
   #フォローしているユーザーを取得
    @follow_users = @user.followings.map { |f| f[:id] }
    @follow_users << current_user.id
    
   #フォローユーザーの投稿のみ表示
    @events_onlyfollow = @all_events.where(user_id: @follow_users).order("created_at DESC")
    # 自分の投稿のみ
    @events = Event.where(user_id: current_user.id)
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])
    @comment = Comment.new
    @comments = @event.comments.includes(:user)
  end

  # GET /events/new
  def new
    @event = Event.new
    @menu = @event.menus.build
    @menu_set = @menu.menu_sets.build
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    index
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: '記録完了' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { redirect_to root_path, notice: '※記録失敗（本文が空白です）' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    @event.destroy
    @event = Event.new(event_params)
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: '記録の変更完了' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: '記録削除' }
      format.json { head :no_content }
    end
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title, :body, :start_date, :end_date, :image, menus_attributes: [:name, :part, menu_sets_attributes:[:number, :number_unit, :rep, :rep_unit]]).merge(user_id: current_user.id)
      
    end

    def move_to_index
      redirect_to action: :index unless user_signed_in?
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(event_id: params[:event_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(event_id: params[:event_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
    @menus = Menu.all
  end

  def new
    @menu = Menu.new
  end

  def create
    Menu.create(menu_params)
  end

  private
  def menu_params
    paramas.requie(:menu).permit(:name)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.search(params[:keyword], current_user.id)
    respond_to do |format|
      format.html
      format.json
    end
  end
  
  def show
    @user = User.find(params[:id])
    @name = @user.name
    @events = @user.events
  end

  def following
    @user  = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/menu_selects_helper.rb
module MenuSelectsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
  end
end

app/views/events/_comment.html.erb
<%= link_to "/users/#{comment.user_id}", class: "show-link" , method: :get do %>
  <div class="Content">
    <div class="Content__MyImg">
      <img src="<%= comment.user.image %>" class="Content__MyImg">
    </div>
    <div class="Content__Body">
      <div class="Content__Body__Info">
        <div class="text-sm"><%= comment.user.name %></div>
        <div class="Content__Body__Info__Date">
          <%= l comment.created_at , format: :short %>
        </div>
      </div>
      <div class="Content__Body__TextField">
        <%= simple_format(comment.text) %>
      </div>
    </div>
  </div>
<% end %>

app/views/events/_event.html.erb
<%= link_to "/events/#{event.id}", class: "show-link", method: :get do %>
  <div class="Content">
    <div class="Content__MyImg">
      <img src="<%= 
      event.user.image %>" class="Content__MyImg">
    </div>
    <div class="Content__Body">
      <div class="Content__Body__Info">
        <div class="Content__Body__Info__Name"><%= event.user.name %></div>
        <div class="Content__Body__Info__Date">
          投稿日時：<%= l event.created_at , format: :short %>
        </div>
      </div>
      <div class="Content__Body__TextField">
        <%= event.title %>
        <%= simple_format(event.body) %>
        <img src="<%= event.image if event.image.present? %>">
      </div>
    <div class="Content__Body__Reaction">
      <div class="Content__Body__Reaction-comment">
        <i class="far fa-comment m1-2"></i> <%= event.comments.count %>
      </div>
      <div class="Content__Body__Reaction-like">
        <i class="fas fa-thumbs-up m1-2"></i> <%= event.liked_users.count %>
      </div>

    </div>
    </div>
  </div>
<% end %>

app/views/events/_form.html.erb
<div class="NewRecord＿Box">
  <%= form_with(model: event, local: true) do |f| %>
    <% if event.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

            <ul>
            <% event.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= f.label :"記録タイトル ※必須" %>
          <%= f.text_field :title, placeholder: "どんなトレーニングをしましたか？",class: "form-control" %>
        </div>

        <div class="field">
          <%= f.label :"トレーニングメモ" %>
          <%= f.text_area :body,class: "form-control", placeholder: "トレーニングでの気づきを書こう" %>
        </div>

        <div class="field">
          <%= f.file_field :image, placeholder: "Image", id: "image",class: "form-control-file" %>
        </div>


      <div class="d-flex justify-content-between">
      <%= link_to_add_association 'メニュー追加', f, :menus,
        class: 'btn btn-success  ml-1 p-1',
        data: {
          association_insertion_node: '#detail-association-insertion-point',
          association_insertion_method: 'append' }
      %>
      <%= link_to '新規メニュー登録', new_menu_select_path, class: "btn btn-outline-success text-right" %>
      </div>
      <div class="form-group" id='detail-association-insertion-point'>
        <%= f.fields_for :menus do |menu| %>
          <%= render 'menu_fields', f: menu %>
          
        <% end %>
      </div>


    <div class="Date_form">
      <div class="field mr-5">
        <%= f.label :"開始日" %>
        <%= f.datetime_select :start_date %>
      </div>

      <div class="field">
        <%= f.label :"終了日" %>
        <%= f.datetime_select :end_date %>
      </div>
    </div>
    <div class="input">
      <%= f.submit "WORK OUTを保存" , id: "Newrecord", class: "btn btn-success"%>
    </div>
  <% end %>
</div>

app/views/events/_menu_fields.html.erb
<div class="nested-fields menus">
  <%= f.hidden_field :id %>
  <div class=" btn btn-light dropdown p-0 mb-1">
    <%= f.collection_select :name, MenuSelect.all, :menu_name, :menu_name, prompt: "種目名を選択", class: 'form-control '%>
  </div>
  
  <%= link_to_remove_association '削除', f, class: 'btn btn-outline-secondary btn-sm p-0' %>
  <%= link_to_add_association 'セット追加', f, :menu_sets,
    class: 'btn btn-success p-0',
    data: {
      data_association_insertion_traversal: 'closest',
      association_insertion_method: 'append' }
    %>


  <div>
    <%= f.fields_for :menu_sets do |menu_set| %>
      <%= render 'menu_set_fields', f: menu_set %>
    <% end %>
  </div>
</div>

app/views/events/_menu_set_fields.html.erb
<div class="nested-fields">
  <%= f.hidden_field :id %>
  <%= f.text_field :number, :placeholder => "重量", :size => "7*30" %>
  <%= f.collection_select :number_unit, NumberUnit.all, :number_unit, :number_unit, prompt: "単位", class: 'form-control' %>
  <%= f.text_field :rep , :placeholder => "回数", :size => "7*30" %>
  <%= f.collection_select :rep_unit, RepUnit.all, :rep_unit, :rep_unit, prompt: "単位", class: 'form-control' %>
  <%= link_to_remove_association '削除', f, class: 'btn btn-outline-secondary btn-sm p-0' %>

</div>

app/views/events/_new.html.erb
<div class="NewRecord" id="NewRecord">
  <div class="NewRecord＿Box">
    <div class="Cancel" id="Cancel">
      <i class="far fa-times-circle"></i>
    </div>    
    <h1>トレーニングを記録する</h1>
    <div class="NewRecord＿Box＿Form">
      <%= render 'form', event: @event %>
    </div>
  </div>
</div>

app/views/events/edit.html.erb
<div class="NewRecord" id="NewRecord">
  <div class="NewRecord＿Box"> 
    <h1>トレーニングを編集する</h1>
    <div class="NewRecord＿Box＿Form">
      <%= render 'form', path: events_path, method: :post, event: @event %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="Main">
  <% @events_onlyfollow.each do |event| %>
    <%= render partial: "event", locals: { event: event } %>
  <% end %>
  <% unless @events_onlyfollow.present? %>
    <div>
      <div class="icon"><%= image_tag "WONロゴ1.png",class: "icon"%></div>
      <div class="caption text-center">
        <h1>Welocome to WON</h1>
        <h3>Work out Noteで<br>トレーニングを記録しよう！</h3>
        <h3>右下の<i class="far fa-edit"></i>から投稿画面へ</h3>
      </div>
    </div>
  <% end %>

<%= link_to  new_event_path , id: "NewRecordBtn", class:"NewBtn" do %>
  <i class="far fa-edit"></i>
<% end %>

</div>

<a href="#" id="btn_scroll_top"></a>

app/views/events/new.html.erb
<div class="NewRecord" id="NewRecord">
  <div class="NewRecord＿Box"> 
    <h1>トレーニングを記録する</h1>
    <div class="NewRecord＿Box＿Form">
      <%= render 'form', path: events_path, method: :post, event: @event %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class ="Show">
  <div class="Content">

    <%= link_to  "/users/#{@event.user_id}" , class: "Content__MyImg"  do %>
      <div class="Content__MyImg">
        <img src="<%= @event.user.image %>" class="Content__MyImg">
      </div>
    <% end %>

    <div class="Content__Body">
      <div class="Content__Body__Info">
        <div class="Content__Body__Info__Name"><%= @event.user.name %>
        </div>
        <div class="Content__Body__Info__Date">
          投稿日時：<%= l @event.created_at %><br>
          開始日時：<%= l @event.start_date %><br>
          終了日時：<%= l @event.end_date %>
        </div>
        <div class="Content__Body__Info__Option">
           <% if user_signed_in? && current_user.id == @event.user_id %>
              <%#= link_to '編集', "/events/#{@event.id}/edit" %> 
              <%= link_to '削除', "/events/#{@event.id}", method: :delete %>
           <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="Show__Main">
    <div class="Show__Main__Title">
      <h1><%= @event.title %></h1>
    </div>
    <div class="Show__Main__Body">
      <%= simple_format(@event.body) %>
    </div>

    <div class="Show__Main__Menu">
      <% @event.menus.each do |menu| %>
        <div class="mb-4  border-bottom">
          <h2 class="mb-2"><%= menu.name %></h2>

          <% menu.menu_sets.each do |menu_set| %>
            <%  if menu_set.number.present? %>  
              <%= menu_set.number %><%= menu_set.number_unit %>×
            <% end %>
            <%  if menu_set.rep.present? %>  
              <%= menu_set.rep %><%= menu_set.rep_unit %>
              /
            <% end %>
          <% end %>

        </div>
        <% end %>
    </div>

    <div class="Show__Main__Img">
      <img src="<%= @event.image if @event.image.present? %>">
    </div>
  </div>
  <%# いいね %>
  <div class="Show__Like">
    <h3>いいね数: <%= @event.likes.count %></h3>
    <% if current_user.already_liked?(@event) %>
      <%= button_to 'いいねを取り消す', event_like_path(@event), method: :delete %>
    <% else %>
      <%= button_to 'いいね', event_likes_path(@event) %>
    <% end %>
    <h2>いいねしたユーザー</h2>
    <% @event.liked_users.each do |user| %>
      <li><%= user.name %></li>
    <% end %>
  </div>
  <%# いいね %>
  <div class="comments">
      <% if @comments %>
        <% @comments.each do |comment| %>
          <%= render partial: "comment", locals: { comment: comment } %>
        <% end %>
      <% end %>
    </div>
  <div class="container comment-form">
      <%= form_with(model: [@event, @comment]) do |f| %>
        <%= f.text_area :text, placeholder: "コメントする", rows: "1" , class: "form-control"%>
        <%= f.submit "コメント送信" , class: "btn btn-outline-success btn-block mt-2" %>
    <% end %>
  </div>
</div>

app/views/menus/_form.html.erb
<div class="NewRecord＿Box">
  <%= form_with(model: menu, local: true) do |form| %>

    <div class="field Menu_form">
      <%= form.label :"メニュー内容" %>
      <%= form.fields_for :menus do |menu| %>
      種目名: <%= menu.text_field :name %>
      部位: <%= menu.text_field :part %>
        <%= menu.fields_for :menu_sets do |menu_set| %>
        重さ: <%= menu_set.text_field :number %>
        回数: <%= menu_set.text_field :rep %>
        <% end %>
      <% end %>
    </div>

    <div class="Date_form">
      <div class="field">
        <%= form.label :start_date %>
        <%= form.datetime_select :start_date %>
      </div>

      <div class="field">
        <%= form.label :end_date %>
        <%= form.datetime_select :end_date %>
      </div>
    </div>

    <div class="input">
      <%= form.submit "メニューを追加" , id: "Menu_add"%>
    </div>

  <% end %>
</div>

app/views/users/_calender.html.erb
<div class="Calender" id="Calender-show">
  <div id="calendar"></div>
</div>

app/views/users/_follow.html.erb
 <%= form_for(current_user.following_relationships.build(following_id: @user.id)) do |f| %>
  <div><%= f.hidden_field :following_id %></div>
  <%= f.submit "フォローする", class: "btn btn-sm btn-success follow-btn" %>
<% end %>

app/views/users/_follow_form.html.erb
 <% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>  

app/views/users/_stats.html.erb
 <% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followings.count %>
    </strong>
    フォロー
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    フォロワー
  </a>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f| %>
  <%= f.submit "フォロー中", class: "btn btn-primary btn-sm follow-btn" %>
<% end %>

app/views/users/index.html.erb
<div class="Main">
  <div class="UsersIndex">

  <div class="User-search">
    <%= form_with url:'/users', method: :get, local: true do |f| %>
      <%= f.label :name, 'ユーザー名から検索' %>
      <%= f.text_field :name, id: "user-search-field" %>
    <% end %>
  </div>
  <div id="user-search-result">
  </div>
  <div class="User-all" id="User-all">
    <h1>全てのユーザー</h1>
    <% @users.each do |user| %>
    <% @user = user %>
    <table>
      <tr>
        <td>  <img src="<%= @user.image %>" class="Content__MyImg"> </td>
        <td>  <%= @user.name %> </td>
        <td><%= link_to '詳細', user_path(user) %></td>
        <td><%= render 'follow_form' %></td>
      </tr>
    </table>
  <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="Main">
  <div class="User">
    <div class="User__Profile">
      <div class="User__Profile__Img">
      <img src="<%= @user.image %>" class="User__Profile__Img">
      </div>
      <div class="User__Profile__Name">
      <%= @user.name %>
      </div>
      <div class="User__Profile__Info">
        <div class="User__Profile__Info__Date">
        <%= @user.name %>さんは<%= l @user.created_at , format: :veryshort%>から利用しています
        </div>
        <div class="User__Profile__Info__Follow">
          <%= render 'follow_form' %>
          <%= render 'stats' %>
        </div>
      </div>
    </div>
  </div>
  
  <ul class="tab">
	<li class="select">記録</li>
	<li>コメント</li>
	<li>いいね</li>
   <% if user_signed_in? %>
      <% if current_page?(current_user) && current_page?(controller: 'users', action: 'show') %>
        <li>カレンダー</li>
      <% end %> 
    <% end %> 
  </ul>

  <ul class="content">
    <li>
    <div class="event-list">
    <% @events.each do |event| %>
      <%= render partial: "events/event", locals: { event: event } %>
    <% end %>
    </li>

    <li class="hide">
      <% @user.comments.each do |comment| %>
        <%= render partial: "events/comment", locals: { comment: comment } %>
      <% end %>
    </li>

    <li class="hide">
      <% @user.liked_events.each do |event| %>
        <%= render partial: "events/event", locals: { event: event } %>
      <% end %>
    </li>

    <li class="hide">
      <%= render partial: "calender", locals: { events: @user_events } %>
    </li>
  </ul>
  
</div>

<a href="#" id="btn_scroll_top"></a>

app/views/users/show_follow.html.erb
<div class="Main">
  <% @user.followings.each do |user| %>
  <table>
  <tr>
    <td>  <img src="<%= user.image %>" class="Content__MyImg"> </td>
    <td>  <%= user.name %> </td>
    <td><%= link_to '詳細', user_path(user) %></td>
  </tr>

  </table>
  <% end %>
</div>

app/views/users/show_follower.html.erb
<div class="Main">
  <% @user.followers.each do |user| %>
  <table>
  <tr>
    <td>  <img src="<%= user.image %>" class="Content__MyImg"> </td>
    <td>  <%= user.name %> </td>
    <td><%= link_to '詳細', user_path(user) %></td>
  </tr>

  </table>
  <% end %>
</div>